# Generated by Django 5.1.4 on 2025-01-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Curly Wigs', 'CURLY WIGS'), ('Straight Wigs', 'STRAIGHT WIGS'), ('Hair Bundles', 'HAIR BUNDLES')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
